#!/usr/bin/env bash
# Script that starts the server and changes the content
ssh -i ~/.ssh/holberton -o StrictHostKeyChecking=no ubuntu@35.231.218.160 'sudo apt-get install -y nginx; sudo /etc/init.d/nginx start; sudo touch /var/www/html/index.html; sudo chmod 777 /var/www/html/index.html; sudo echo "Holberton School" > /var/www/html/index.html; sudo rm /var/www/html/index.nginx-debian.html'
