#!/usr/bin/env bash
# Script that starts the server and changes the content
sudo apt-get update -y
sudo apt-get install -y nginx
sudo /etc/init.d/nginx start
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
