#!/usr/bin/env bash
# Script that starts the server and changes the content
sudo apt-get update -y
sudo apt-get install -y nginx
sudo /etc/init.d/nginx start
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html
