#!/usr/bin/env bash
# script that creates a redirect
sudo apt-get update -y
sudo apt-get install -y nginx 

redirection="\tlocation = /redirect_me{\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\t\n\t}"
sed -i "71i\\$redirection" /etc/nginx/sites-enabled/default

service nginx restart
