#!/usr/bin/env bash
sudo apt-get update -y
sudo apt-get install -y nginx
sudo sed -i -e "s/^server {$/server {\n\tadd_header X-Served-By \$HOSTNAME;/g" /etc/nginx/sites-available/default
sudo service nginx restart
