#!/usr/bin/env bash
#Implementing if, elif and else statements

x=1
while [ $x -lt 11 ]
do
	if [ $x = 4 ]
	then
		echo "bad luck"
	elif [ $x = 8 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	((x++))
done

