#!/usr/bin/env bash
#Implementing if, elif and else statements

x=1
while [ $x -lt 21 ]
do
	echo $x
	case $x in
		4) echo "bad luck from China" ;;
		9) echo "bad luck from Japan" ;;
		17) echo "bad luck from Italia" ;;
	esac
	((x++))
done

